// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeatroApi.Data;

#nullable disable

namespace TeatroApi.Data.Migrations
{
    [DbContext(typeof(TeatroContext))]
    partial class TeatroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeatroApi.Models.Asientos", b =>
                {
                    b.Property<int>("IdSeats")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("ObraIdPlay")
                        .HasColumnType("int");

                    b.Property<int?>("SesionIdSeats")
                        .HasColumnType("int");

                    b.Property<int?>("SesionIdSesion")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdSeats", "IdUser");

                    b.HasIndex("ObraIdPlay");

                    b.HasIndex("SesionIdSesion", "SesionIdSeats");

                    b.ToTable("Asientos");

                    b.HasData(
                        new
                        {
                            IdSeats = 1,
                            IdUser = 0,
                            Number = 1,
                            Status = true
                        },
                        new
                        {
                            IdSeats = 2,
                            IdUser = 0,
                            Number = 2,
                            Status = false
                        },
                        new
                        {
                            IdSeats = 3,
                            IdUser = 0,
                            Number = 3,
                            Status = true
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Obra", b =>
                {
                    b.Property<int>("IdPlay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlay"));

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPlay");

                    b.ToTable("Obras");

                    b.HasData(
                        new
                        {
                            IdPlay = 1,
                            Date = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Una descripción",
                            Duration = "2h",
                            Name = "Lalaland",
                            Photo = "https://picsum.photos/200/300",
                            Price = 100m
                        },
                        new
                        {
                            IdPlay = 2,
                            Date = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Otra descripción",
                            Duration = "2h",
                            Name = "Los 100",
                            Photo = "https://picsum.photos/200/300",
                            Price = 300m
                        },
                        new
                        {
                            IdPlay = 3,
                            Date = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Otra más",
                            Duration = "2h",
                            Name = "Fiesta",
                            Photo = "https://picsum.photos/200/300",
                            Price = 200m
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Reserva", b =>
                {
                    b.Property<int>("IdReservation")
                        .HasColumnType("int");

                    b.Property<int>("IdPlay")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservationPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReservation", "IdPlay");

                    b.HasIndex("IdPlay");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            IdReservation = 1,
                            IdPlay = 1,
                            IdUser = 1,
                            ReservationDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationPrice = "100",
                            UserEmail = "user1@example.com"
                        },
                        new
                        {
                            IdReservation = 2,
                            IdPlay = 1,
                            IdUser = 2,
                            ReservationDate = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationPrice = "200",
                            UserEmail = "user2@example.com"
                        },
                        new
                        {
                            IdReservation = 3,
                            IdPlay = 1,
                            IdUser = 3,
                            ReservationDate = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationPrice = "300",
                            UserEmail = "user3@example.com"
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Sesion", b =>
                {
                    b.Property<int>("IdSesion")
                        .HasColumnType("int");

                    b.Property<int>("IdSeats")
                        .HasColumnType("int");

                    b.Property<int>("IdPlay")
                        .HasColumnType("int");

                    b.Property<string>("SesionTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSesion", "IdSeats");

                    b.ToTable("Sesiones");

                    b.HasData(
                        new
                        {
                            IdSesion = 1,
                            IdSeats = 1,
                            IdPlay = 1,
                            SesionTime = "16:00-17:00"
                        },
                        new
                        {
                            IdSesion = 2,
                            IdSeats = 2,
                            IdPlay = 2,
                            SesionTime = "19:00-20:00"
                        },
                        new
                        {
                            IdSesion = 3,
                            IdSeats = 3,
                            IdPlay = 3,
                            SesionTime = "22:00-23:00"
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Usuario", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            Email = "hola1@gmail.com",
                            Password = "123",
                            Rol = 1,
                            UserName = "cosmar"
                        },
                        new
                        {
                            IdUser = 2,
                            Email = "hola2@gmail.com",
                            Password = "123",
                            Rol = 2,
                            UserName = "cosmari"
                        },
                        new
                        {
                            IdUser = 3,
                            Email = "hola3@gmail.com",
                            Password = "123",
                            Rol = 2,
                            UserName = "cosmaro"
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Asientos", b =>
                {
                    b.HasOne("TeatroApi.Models.Obra", null)
                        .WithMany("Asientos")
                        .HasForeignKey("ObraIdPlay");

                    b.HasOne("TeatroApi.Models.Sesion", null)
                        .WithMany("Seats")
                        .HasForeignKey("SesionIdSesion", "SesionIdSeats");
                });

            modelBuilder.Entity("TeatroApi.Models.Reserva", b =>
                {
                    b.HasOne("TeatroApi.Models.Obra", "Obra")
                        .WithMany("Reservas")
                        .HasForeignKey("IdPlay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("TeatroApi.Models.Sesion", b =>
                {
                    b.HasOne("TeatroApi.Models.Obra", "Obra")
                        .WithMany("Sesiones")
                        .HasForeignKey("IdSesion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("TeatroApi.Models.Obra", b =>
                {
                    b.Navigation("Asientos");

                    b.Navigation("Reservas");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("TeatroApi.Models.Sesion", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
